name: Build, test & deploy .NET API/Application

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-build-n-test:
    name: Call Build & Test Workflow
    uses: Nykredit/.github/.github/workflows/ci-dotnet-build-n-test.yml@main
    with:
      sonar-project-id: 'id-of-project-in-sonarqube - SET TO EMPTY STRING TO SKIP SONARQUBE'
    secrets: 
      sonar-api-key: ${{secrets.SONAR_APIKEY}}
      nexus-user: ${{secrets.NEXUS_USER}}
      nexus-password: ${{ secrets.NEXUS_PASSWORD }}

  call-create-release:
    name: Call Create Tagged Release Workflow
    needs: [ call-build-n-test ]
    uses: Nykredit/.github/.github/workflows/ci-dotnet-create-release.yml@main
    with: 
      caller-event: ${{ github.event_name }}

  call-deploy:
    name: Call Deploy Workflow
    uses: Nykredit/.github/.github/workflows/deploy-dotnet-onprem-octopus.yml@main
    needs: [ call-create-release ]
    with:
      package-id: 'INSERT PACKAGE ID'
      main-project: 'INSERT MAIN PROJECT'
      octopus-project: 'INSERT OCTOPUS PROJECT'
      octopus-environment: 'Test'
    secrets: 
      sonar-api-key: ${{secrets.SONAR_APIKEY}}
      nexus-user: ${{secrets.NEXUS_USER}}
      nexus-password: ${{ secrets.NEXUS_PASSWORD }}
      octopus-api-key: ${{ secrets.OCTOPUS_API_KEY }}
