name: Build & test .NET solution + create tagged release

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-build-n-test:
    name: Call Build & Test Workflow
    uses: Nykredit/.github/.github/workflows/ci-dotnet-build-n-test.yml@main
    with:
      sonar-project-id: 'id-of-project-in-sonarqube'
    secrets: 
      sonar-api-key: ${{secrets.SONAR_APIKEY}}
      nexus-user: ${{secrets.NEXUS_USER}}
      nexus-password: ${{ secrets.NEXUS_PASSWORD }}

  call-create-release:
    name: Call Create Tagged Release Workflow
    needs: [ call-build-n-test ]
    uses: Nykredit/.github/.github/workflows/ci-dotnet-create-release.yml@main
