name: Deploy .NET to on-prem Octopus installation

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  define-version-number:
    name: Calculate SemVer
    runs-on: ubuntu-24.04
    outputs:
      package-version: ${{ steps.version_step.outputs.fullSemVer }}
    steps:  
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.3
      with:
        versionSpec: '6.0.x'
        preferLatestVersion: true
    - name: Determine SemVer
      id: version_step
      uses: gittools/actions/gitversion/execute@v3.1.3
    
  call-build-n-test:
    name: Call Build & Execute Workflow
    needs: [ define-version-number ]
    uses: Nykredit/.github/.github/workflows/ci-dotnet-build-n-test.yml@main
    with:
      package-version: ${{ needs.define-version-number.outputs.package-version }}
      sonar-project-id: 'id-of-project-in-sonarqube'
    secrets: 
      sonar-api-key: ${{secrets.SONAR_APIKEY}}
      nexus-user: ${{secrets.NEXUS_USER}}
      nexus-password: ${{ secrets.NEXUS_PASSWORD }}


  call-build-n-publish:
    name: Call Build & Publish NuGet Packages
    needs: [ define-version-number, call-build-n-test ]
    uses: Nykredit/.github/.github/workflows/ci-dotnet-build-n-publish.yml@main
    with:
      package-version: ${{ needs.define-version-number.outputs.package-version }}
    secrets: 
      nexus-user: ${{secrets.NEXUS_USER}}
      nexus-password: ${{ secrets.NEXUS_PASSWORD }}
