name: Deploy .NET to on-prem Octopus installation

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SONAR_PROJECT_ID: 'id-of-project-in-sonarqube'
  

jobs:
  define-version-number:
    name: Calculate SemVer
    runs-on: ubuntu-24.04
    outputs:
      package-version: ${{ steps.yeet_version_no.semmie}}
    steps:  
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.3
      with:
        versionSpec: '6.0.x'
        preferLatestVersion: true
    - name: Determine SemVer
      uses: gittools/actions/gitversion/execute@v3.1.3
    - name: Output Package SemVer
      id: yeet_version_no
      run: echo "semmie=$FULLSEMVER" >> "$GITHUB_OUTPUT"
    
  call-build-n-test:
    name: Call Build & Execute Workflow
    environment: hell
    needs: [ define-version-number ]
    uses: Nykredit/.github/actions/ci-dotnet-build-n-test@main
    with:
      package-version: ${{ needs.define-version-number.package-version }}
      sonar-project-id: ${{ env.sonar-project-id }}
    secrets: 
      sonar-api-key: ${{secrets.SONAR_APIKEY}}
      nexus-user: ${{secrets.NEXUS_USER}}
      nexus-password: ${{ secrets.NEXUS_PASSWORD }}


  call-build-n-publish:
    name: Call Build & Publish NuGet Packages
    environment: hell
    needs: [ define-version-number, call-build-n-test ]
    uses: Nykredit/.github/actions/ci-dotnet-build-n-publish@main
    with:
      package-version: ${{ needs.define-version-number.package-version }}
    secrets: 
      nexus-user: ${{secrets.NEXUS_USER}}
      nexus-password: ${{ secrets.NEXUS_PASSWORD }}
