name: Create tagged .NET release 

on:
  workflow_call:
    inputs:
      caller-event:
        description: 'Which event caused execution of caller workflow'
        required: true
        type: string
    
jobs:
  create-tagged-version:
    permissions:
      id-token: write
      contents: write
      repository-projects: write    
    name: Calculate SemVer
    runs-on: ubuntu-24.04
    steps:  
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.3
      with:
        versionSpec: '6.0.x'
    - name: Determine SemVer
      id: version_step
      uses: gittools/actions/gitversion/execute@v3.1.3
    - name: Increment SemVer
      id: version_increment
      shell: pwsh
      env: 
        currentsemver: ${{steps.version_step.outputs.majorMinorPatch }}  
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}    
        this_eventname: ${{ github.event_name}}
        callerevent: ${{ inputs.caller-event}}
      run: |
         $semverString = "$Env:currentsemver"
         $semver =  [version]$semverString
         $major = $semver.Major
         $minor = $semver.Minor
         $build = $semver.Build
         if($Env:callerevent -eq 'workflow_dispatch') 
         {
            $build = $build + 1
         }
         $nextSemver = "$major.$minor.$build"
         Write-Host "Will use next SemVer=$nextSemver" 
         $tagName = "v$nextSemver"
         Write-Host "Using tag name $tagName" 
         gh release create $tagName   
